# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmQuota < Formula
  desc "Terminal UI for local Claude Code and Codex quota windows"
  homepage "https://github.com/robbell5/llm-quota"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robbell5/llm-quota/releases/download/v0.3.1/llm-quota_0.3.1_darwin_amd64.tar.gz"
      sha256 "438be7bcd8fe7a7527a153993ba2bb5e7f715bc8b0980ac71c8970412ed0d91d"

      define_method(:install) do
        bin.install "llm-quota"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robbell5/llm-quota/releases/download/v0.3.1/llm-quota_0.3.1_darwin_arm64.tar.gz"
      sha256 "b48e0db4e300a2ed9c8d52c0b28836751bc9c6e204b5aff38984a6131df93b90"

      define_method(:install) do
        bin.install "llm-quota"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robbell5/llm-quota/releases/download/v0.3.1/llm-quota_0.3.1_linux_amd64.tar.gz"
      sha256 "c52895de126382c28fd07312cf1f4269487a528d92805f1ab9d4bb56b2e5441a"
      define_method(:install) do
        bin.install "llm-quota"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robbell5/llm-quota/releases/download/v0.3.1/llm-quota_0.3.1_linux_arm64.tar.gz"
      sha256 "438da71e43e9f0419b2d238be5251f04e3e1c7f8735091583eac3394ac4cf260"
      define_method(:install) do
        bin.install "llm-quota"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/llm-quota --version")
  end
end
